[package]
name = "bit-field_macro"
version = "0.1.0"
edition = "2021"

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = "2.0"

[dev-dependencies]
bit-field = { version = "0.1", path = "../bit-field" }

[lib]
proc-macro = true
